### PR TITLE
Adding BBR settings tree to get automatic baseline in mPMT analysis

### PR DESCRIPTION
**Pull request by thomaslindner**
This is a pull request to solve issue #12 .  

Compared to my suggestions in issue #12 I decided to go for a different way of getting the baseline for mPMT analysis in ptf-analysis.  This is necessary because each channel has a different baseline for the mPMT mainboard (aka Big Red Board, aka BRB).  The method is as follows (steps 4 and 5 are what are in this pulse request):

1) In the online analysis we calculate a baseline for every channel periodically and store it in the online database.

2) When we write a MIDAS file, the state of the ODB gets stored at the start of the run.  This copy of the ODB stores the baselines.

3) In midas2root we save the baselines (and a couple other parameters like HV settings) in a special tree (called settings tree).  This tree has only one event and is just used to store some values from the ODB.

4. In ptf-analysis I have added a new singleton class BrbSettingsTree, which is meant to store this ODB information; the online baselines in this case.  The singleton opens the tree by calling a method through the wrapper instance.  Specifically by calling
`  wrapper.LoadBrbSettingsTree();
`
Calling this will load the ODB values in the singleton, which can then be used throughout the analysis.

5. I have modified the mPMT pulse finding and pulse fitting to use these values of the baseline

### CODE REVIEW

**Comment by vgousyleblanc** [comment]
Okay, so if I understand correctly, this new tree is created each time we run the analysis. I suppose that if we run it for only SK PMT we can then just modify the wrapper ? Or it will work anyway but with only one channel or they are specific channel for mPMT (this is what I think but just want to make sure. Also, really naive question but what is a baseline ?

**Comment by thomaslindner** [comment]
> Okay, so if I understand correctly, this new tree is created each time we run the analysis. I suppose that if we run it for only SK PMT we can then just modify the wrapper ? Or it will work anyway but with only one channel or they are specific channel for mPMT (this is what I think but just want to make sure. Also, really naive question but what is a baseline ?

This change won't do anything for the PTF analysis right now.  The PTF midas2root converter doesn't make a 'settings_tree' in the original ROOT file yet (though I think we should add one to say coil currents and PMT HV later).  Since it doesn't have a settings_tree this bunch of code won't do anything for the PTF analysis.  In any case, you would need to call 

`wrapper.LoadBrbSettingsTree();`

for it to even try to do anything.

**Review by vgousyleblanc — APPROVED** [review]
Great, in that case I approve the merge !

**Comment by thomaslindner** [comment]
I'm going to go ahead and merge this pull request from last year, since we keep getting tripped up by this.

**Pull request merged**
