### PR TITLE
Settings tree

### PR DESCRIPTION
**Pull request by koeri-ch**
This branch has the code to open up the _setting_tree_ from the root file.

### CODE REVIEW

**Comment by pdeperio** [comment]
@koeri-ch FYI conflicts to be resolved here...

**Comment by pdeperio** [comment]
@koeri-ch is this still needed?

**Comment by koeri-ch** [comment]
@thomaslindner Is this branch even necessary anymore? this was just a suggestion on how to open the BRB settings, but I never used it myself. not sure if this was used by anybody or if it is the most appropriate way to do so.

**Comment by koeri-ch** [comment]
I'd vote for not keeping this branch. Please feel free.

**Pull request closed without merging**
